
% Function for setting model specifications for the enz cat model.

% A struct is returned which contains all important properties of the
% model for doing a multi-start optimization

function ModelSpec = writeModelSpec_EC()

    multistarts = 10;
    
    ModelSpec = struct(...
        'nTimepoints', 50, ...
        'nMeasure', 1000, ...
        'sigma2', 0.05^2, ...
        'lowerBound', -10, ...
        'upperBound', 5, ...
        'theta', [1 -3 0 -5]', ...
        'multistarts', multistarts, ...
        'par0', lhsdesign(multistarts, 4, 'smooth', 'off')');

end