
% Function in which common options for tuning parameters for minibatch
% optimization algorithms are set
%
% The algorithm must be passed to the function
% A struct is returned.

function OptimizerOptions = getOptimizerOptions(algorithm, miniBatchSize, ModelSpec)

    if strcmp(algorithm, 'fmincon')
        % fmincon options are set
        OptimizerOptions = optimset(...
                'algorithm', 'interior-point',...
                'display', 'iter', ...
                'TolX', 1e-12, ...
                'TolFun', 1e-10, ...
                'TolGrad', 1e-6, ...
                'GradObj', 'on', ...
                'MaxIter', 2000, ...
                'PrecondBandWidth', inf);
            
    else
        % the generic options for delos are set
        OptimizerOptions(1) = struct(...
                'stochastic', true,...
                'miniBatchSize', miniBatchSize, ...
                'dataSetSize', ModelSpec.nMeasure, ...
                'barrier', 'log-barrier', ...
                'display', 'file', ...
                'outputID', [], ...
                'restriction', true, ...
                'reportInterval', 1, ...
                'method', algorithm);
    end
    
    switch algorithm
        case 'rmsprop'
            
        case 'rmspropnesterov'
            
        case 'adam'
            OptimizerOptions(1).MaxIter = 400;
            OptimizerOptions(1).hyperparams = struct(...
                'rho1', 0.5, ...
                'rho2', 0.9, ...
                'delta', 1e-8, ...
                'eps0', 0.1, ...
                'epsTau', 1e-5, ...
                'tau', 250);
            
            counter = 0;
            for rho1 = [0.5, 0.8, 0.9, 0.99, 0.999]
                for rho2 = [0.5, 0.8, 0.9, 0.99, 0.999]
                    for eps0 = [0.1, 0.025]
                        counter = counter + 1;
                        OptimizerOptions(counter) = OptimizerOptions(1);
                        OptimizerOptions(counter).hyperparams.rho1 = rho1;
                        OptimizerOptions(counter).hyperparams.rho2 = rho2;
                        OptimizerOptions(counter).hyperparams.eps0 = eps0;
                    end
                end
            end
            
        case 'adadelta'
            
    end
end